services:
  - type: web
    name: systemb-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PROJECT_NAME
        value: Biometric Gesture Authentication
      - key: VERSION
        value: 2.0.0
      - key: API_V1_STR
        value: /api/v1